//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDataServiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Emps = new HashSet<Emp>();
        }
    
        public int AddressId { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> BuildingNo { get; set; }
    
        public virtual ICollection<Emp> Emps { get; set; }
    }
}
