//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDataServiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EmployeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Department Department { get; set; }
    }
}
