// This file is autogenerated from the T4 template
// Generated on 2/10/2014 2:10:18 AM
	//The file is created by Abhishek Sur 

	public class Country
	{
		public string CountryId { get; set; }
		public string CountryName { get; set; }
		public string Capital { get; set; }
	}
	public class States
	{
		public string StateId { get; set; }
		public string CountryId { get; set; }
		public string StateName { get; set; }
	}
